# Generated by Django 6.0.2 on 2026-02-19 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emocion',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='registroestadoanimo',
            name='estado_animo',
        ),
        migrations.RemoveField(
            model_name='registroestadoanimo',
            name='usuario',
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CategoriaEmocion',
        ),
        migrations.DeleteModel(
            name='EstadoAnimo',
        ),
        migrations.DeleteModel(
            name='RegistroEstadoAnimo',
        ),
    ]
