# Generated by Django 6.0.2 on 2026-02-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar', '0005_respuestaalumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='notapsicologo',
            name='leido',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='RespuestaAlumno',
        ),
    ]
