# Generated by Django 5.2 on 2026-02-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar', '0007_alter_auditoria_id_alter_diario_id_alter_emocion_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diario',
            name='estado_animo',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
