# Generated by Django 6.0.3 on 2026-05-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar', '0009_alter_auditoria_id_alter_diario_id_alter_emocion_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emocion',
            name='emoji',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
